// File generated by FlutterFire CLI.
// This is a PLACEHOLDER file and should be replaced by running:
// flutterfire configure --project=your-firebase-project-id
//
// Contains placeholder Firebase options required by the app to compile
// until real configuration is added.

import 'dart:io';
import 'package:firebase_core/firebase_core.dart';

/// Placeholder Firebase options until real configuration is generated
/// Replace this file by running: flutterfire configure
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (Platform.isAndroid) {
      return android;
    }
    throw UnsupportedError(
      'DefaultFirebaseOptions have not been configured for this platform - '
      'please run "flutterfire configure" to generate options',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAblNtytVwVRgr7LlmfhJu2oM-9gBWrjfw',
    appId: '1:201900119855:android:f3fe266f579e4cc76533da',
    messagingSenderId: '201900119855',
    projectId: 'nory-shop-dev',
    storageBucket: 'nory-shop-dev.firebasestorage.app',
  );

}