// File generated by FlutterFire CLI.
// This is a PLACEHOLDER file and should be replaced by running:
// flutterfire configure --project=your-firebase-project-id
//
// Contains placeholder Firebase options required by the app to compile
// until real configuration is added.

import 'dart:io';
import 'package:firebase_core/firebase_core.dart';

/// Placeholder Firebase options until real configuration is generated
/// Replace this file by running: flutterfire configure
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (Platform.isAndroid) {
      return android;
    }
    throw UnsupportedError(
      'DefaultFirebaseOptions have not been configured for this platform - '
      'please run "flutterfire configure" to generate options',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'placeholder-api-key',
    appId: '1:000000000000:android:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'placeholder-project',
    storageBucket: 'placeholder-project.appspot.com',
  );
}
